development:
  adapter: postgresql
  encoding: unicode
  database: appsterdam_development
  template: template0
  pool: 5
  username: <%= ENV['USER'] %>
  min_messages: warning
test:
  adapter: postgresql
  encoding: unicode
  database: appsterdam_test
  template: template0
  pool: 5
  username: <%= ENV['USER'] %>
  min_messages: warning