development:
  adapter: mysql2
  database: appsterdam_site
  username: devuser
  password:
  template: template0
  pool: 5
  username: <%= ENV['USER'] %>
  min_messages: warning

test:
  adapter: mysql2
  database: appsterdam_site3
  password:
  username: devuser
  template: template0
  pool: 5
  username: <%= ENV['USER'] %>
  min_messages: warning